name: 'Terrascan'

on:
  push:
   branches: master
   
jobs:
  terrascan:
     name: 'terrascan'
     runs-on: ubuntu-latest
     steps: 
       - name: 'Run Terrascan'
         run: |
           git clone https://github.com/accurics/terrascan.git
           cd terrascan
           make build 
           ./bin/terrascan
           cp /Users/intelycorellc/terraform-ec2/east/"how to create ec2 instance"/*.tf . 
           ./bin/terrascan scan -t aws
