name: 'Terrascan'

on:
  push:
   branches: master
   
jobs:     
  terrascan:
     name: 'terrascan'
     runs-on: ubuntu-latest
     steps: 
       - name: Checkout
         uses: actions/checkout@v2
       - name: 'Install Terrascan'
         run: |
           set -x 
           git clone https://github.com/accurics/terrascan.git
           cd terrascan
           make build 
           ./bin/terrascan
       - name: 'Run Terrascan' 
         run: |
           set -x
           ls
           pwd
           find . -name "*.tf"
           cp ./east/"how to create ec2 instance"/main.tf terrascan
           cd terrascan
           ./bin/terrascan scan -t aws
              
